name: slack_history_keeper_frontend
version: 0.0.0
description:
author:
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.22'
  browser: '^0.10.0+2'
  http: "^0.11.3+2"
  sass: '^0.4.2'
  markdown: '^0.11.1'
  slack_history_keeper_shared:
    path: ../shared
  event_bus: '^0.4.1'
  script_inliner: "^1.0.0"
  dart_to_js_script_rewriter: "^0.1.0+4"
dependency_overrides:
  code_transformers: 0.3.1
dev_dependencies:
  test: '^0.12.15+9'
  mockito: '^1.0.1'
transformers:
  - angular2:
      entry_points: web/main.dart
      resolved_identifiers:
              EventBus: 'package:event_bus/event_bus.dart'
  - script_inliner
  - dart_to_js_script_rewriter
  - sass:
      style: compact
  - $dart2js:
      minify: true
      commandLineOptions: [--dump-info]
