name: slack_history_keeper_frontend
version: 0.0.0
description:
author:
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.0'
  browser: '^0.10.0+2'
  http: "^0.11.3+2"
  sass: '^0.4.2'
  markdown: "^0.9.0"
  slack_history_keeper_shared:
    path: ../shared
  event_bus: "^0.4.1"
  script_inliner: "^1.0.0"
dependency_overrides:
  code_transformers: 0.3.1
  analyzer: 0.27.0
dev_dependencies:
  test: "^0.12.6+1"
  mockito: "^0.11.0"
transformers:
  - angular2:
      entry_points: web/main.dart
  - sass:
      style: compact
  - $dart2js:
      minify: true
      commandLineOptions: [--dump-info]
  - script_inliner
