name: slack_history_keeper_frontend
version: 0.0.0
description:
author:
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.0'
  browser: '^0.10.0+2'
  http: "^0.11.3+2"
  slack_history_keeper_shared:
    path: ../shared
dependency_overrides:
  redstone_mapper:
    git: https://github.com/redstone-dart/redstone_mapper.git
  redstone_mapper_mongo:
    git: https://github.com/redstone-dart/redstone_mapper_mongo.git
  code_transformers: 0.3.1
  analyzer: 0.27.0
transformers:
- angular2:
    entry_points: web/main.dart
- redstone_mapper
