name: slack_history_keeper_backend
version: 0.0.1
description: A sample command-line application.
author: Joel Trottier-Hebert <iamquebecois@gmail.com>
homepage: http://stacktrace.ca

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: "^0.11.3+2"
  logging: "^0.11.1+1"
  connection_pool: "^0.1.0+2"
  slack_history_keeper_shared:
    path: ../shared
  mongo_dart: '0.2.9'
dependency_overrides:
  redstone:
    git: https://github.com/redstone-dart/redstone.git
  di:
    git: https://github.com/Pacane/di.dart.git
  mongo_dart:
    git: https://github.com/meriouma/mongo_dart.git
  mongo_dart_query: "^0.2.2"
  analyzer: 0.27.0
dev_dependencies:
  test: "^0.12.4+9"
