name: slack_history_keeper_backend
version: 0.0.1
description: A sample command-line application.
author: Joel Trottier-Hebert <iamquebecois@gmail.com>
homepage: http://stacktrace.ca

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: "^0.11.3+2"
  logging: "^0.11.1+1"
  connection_pool: "^0.1.0+2"
  slack_history_keeper_shared:
    path: ../shared
  mongo_dart: '^0.2.5-beta'
dependency_overrides:
  redstone:
    git: https://github.com/redstone-dart/redstone.git
  redstone_mapper:
    git: https://github.com/redstone-dart/redstone_mapper.git
  redstone_mapper_mongo:
    git: https://github.com/redstone-dart/redstone_mapper_mongo.git
  di:
    git: https://github.com/Pacane/di.dart.git
dev_dependencies:
  test: "^0.12.4+9"
transformers:
- redstone_mapper
