name: slack_history_keeper_backend
version: 0.0.1
description: A sample command-line application.
author: Joel Trottier-Hebert <iamquebecois@gmail.com>
homepage: http://stacktrace.ca

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: '>=0.11.3+9 <0.12.0'
  logging: "^0.11.1+1"
  connection_pool: "^0.1.0+2"
  slack_history_keeper_shared:
    path: ../shared
  mongo_dart: '>=0.2.10 <0.3.0'
  redstone: '>=0.6.7 <0.7.0'
dependency_overrides:
  analyzer: 0.27.0
dev_dependencies:
  test: "^0.12.4+9"
