name: slack_history_keeper_shared
version: 0.0.0
description:
author:
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  quiver: "^0.21.4"
  dogma_convert: '^0.0.1'
  dogma_codegen: "^0.0.1"
dependency_overrides:
  analyzer: 0.27.1
